import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { Sarabun } from "next/font/google";
import { Pinyon_Script } from "next/font/google";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { setRequestLocale } from "next-intl/server";
import { Toaster } from "sonner";
import { routing } from "@/i18n/routing";
import Providers from "./../../components/providers/index";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});
const zain = localFont({
  src: "./fonts/Zain-Regular.ttf",
  variable: "--font-zain",
});
const diwany = localFont({
  src: "./fonts/FS_Diwany.ttf",
  variable: "--font-diwany",
});
const edwardian = localFont({
  src: "./fonts/edwardianscriptitc.ttf",
  variable: "--font-edwardian",
});

// Sarabun font
const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-sarabun",
});
// Pinyon_Script font
const pinyon = Pinyon_Script({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--font-pinyon",
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = params;
  // Enable static rendering
  setRequestLocale(locale);
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${diwany.variable} ${edwardian.variable} ${geistMono.variable} ${zain.variable} ${diwany.variable} ${pinyon.variable} ${sarabun.variable} antialiased dark:bg-zinc-800`}
      >
        {/* Providers */}
        <Providers>
          {/* Main children  */}
          <main>{children}</main>

          {/* Toast notifications */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
